spring:
  application:
    name: nx-auto-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://nx-auto-ms-customer
          predicates:
          - Path=/customer/**
        - id: shop
          uri: lb://nx-auto-ms-shop
          predicates:
          - Path=/shop/**
  main:
    web-application-type: reactive
server:
  port: 8080
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8989/eureka
